Controllers/VideoController.cs
using DulkyVideo.Authorization;
using DulkyVideo.Services.Intrerfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Twilio.Jwt.AccessToken;

namespace DulkyVideo.Controllers
{
    public class VideoController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IVideoService _videoService;

        public VideoController(UserManager<ApplicationUser> userManager, IVideoService videoService)
        {
            _userManager = userManager;
            _videoService = videoService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet()]
        public async Task<IActionResult> GetAccessTokenToCreateRoom(string roomName) 
        {
            var user = await _userManager.GetUserAsync(User);
            var response = await _videoService.GetAccessTokenToCreateRoom(user.UserName, roomName);
           
            return Json(response); 
        }

        [HttpGet]
        public async Task<IActionResult> GetContacts()
        {
            var user = await _userManager.GetUserAsync(User);
            var result = _videoService.GetContacts(user.Id);
            return PartialView("_SelectRoomPartial", result);
        }

        [HttpGet()]
        public async Task<IActionResult> GetAccessTokenToJoinRoom(string roomName)
        {
            var user = await _userManager.GetUserAsync(User);
            var response = _videoService.GetAccessTokenToJoinRoom(Convert.ToString(user.Id), user.UserName, roomName);
            return Json(response);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DulkyVideo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/bellannimation.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    @RenderSection("Style", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DulkyVideo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">Video</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - DulkyVideo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//media.twiliocdn.com/sdk/js/video/releases/2.7.2/twilio-video.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.24.0/firebase-messaging.js"></script>
    <script src="~/js/Firebase/setup.js"></script>

    <script>
        function bellClicked() {
            //window.value = "ringingButtonClicked";
            localStorage.setItem("bellButton", "clicked");
            //var elem = document.getElementById('ringingButton');
            //$("#ringingButton").attr('myattr', 'true');
            //var elem2 = document.getElementById('ringingButton');
            ////

            //var pom1 = document.getElementById('ringingButton');
            //var pom2 = document.getElementById('ringingButton').getAttribute('myattr')
            //if (document.getElementById('ringingButton').getAttribute('myattr') === 'true') {
            //    console.log("BELLL");
            //}
            //else {
            //    console.log("NO BELLLLL");
            //}
            window.location = "/Video";
        }
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>